services:
  weather-app:
    build: .
    container_name: weather-forecast-container
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_BROWSER_SERVER_ADDRESS=localhost
      - PYTHONUNBUFFERED=1
    # Note: 'volumes' removed as per your requirement to use image-internal files